# Generated by Django 5.2.12 on 2026-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_ticket_email_alter_ticket_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sc",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
