# Generated by Django 5.2.12 on 2026-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_sc_logo_ticket_passenger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
