# Generated by Django 5.2.12 on 2026-09-18 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pasenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("registered_time", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(max_length=128)),
                ("age", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
