# Generated by Django 5.2.17 on 2026-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_pasenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
